version: '3.8'

services:
  # Grafana Agent - handles everything securely
  grafana-agent:
    image: grafana/agent:latest
    container_name: pandacare-grafana-agent
    ports:
      - "12345:12345"
    volumes:
      - ./monitoring/grafana-agent.yml:/etc/grafana-agent.yml
    environment:
      - GRAFANA_CLOUD_USER=${GRAFANA_CLOUD_USER}
      - GRAFANA_CLOUD_API_KEY=${GRAFANA_TOKEN}
    command:
      - '-config.file=/etc/grafana-agent.yml'
      - '-metrics.wal-directory=/tmp/grafana-agent-wal'
    restart: unless-stopped
    networks:
      - monitoring

  # Local Grafana for development (optional)
  grafana-local:
    image: grafana/grafana:latest
    container_name: pandacare-grafana-local
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_LOCAL_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_LOCAL_PASSWORD:-pandacare123}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - monitoring

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: pandacare-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  grafana_data:

networks:
  monitoring:
    driver: bridge