version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pandacare-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - pandacare-network
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PandaCare Auth-Profile Service
  auth-profile:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pandacare-auth-profile
    environment:
      # Database Configuration
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}

      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}

      # Application Configuration
      - SERVER_PORT=${SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

      # Rating Service Integration
      - RATING_URL=${RATING_URL}

      # Logging Configuration
      - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}
      - LOGGING_LEVEL_AUTH_PROFILE=${LOGGING_LEVEL_AUTH_PROFILE:-DEBUG}
      - LOGGING_FILE_NAME=${LOGGING_FILE_NAME:-/app/logs/auth-profile.log}

      # Monitoring Configuration
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:-health,prometheus,metrics,info}
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:-when_authorized}
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED:-true}

      # Performance Configuration
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:-10}
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:-50}
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:-30000}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - app_logs:/app/logs
      - ./logs:/app/logs  # Mount host directory for easy log access
    networks:
      - pandacare-network
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Give more time for Spring Boot to start
    deploy:
      resources:
        limits:
          memory: ${CONTAINER_MEMORY_LIMIT:-2G}
          cpus: ${CONTAINER_CPU_LIMIT:-1.0} # Corrected
        reservations:
          memory: ${CONTAINER_MEMORY_RESERVATION:-1G}
          cpus: ${CONTAINER_CPU_RESERVATION:-0.5} # Corrected

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local

networks:
  pandacare-network:
    driver: bridge
    name: pandacare-network