# monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: '${CLUSTER:-pandacare-local}'
    environment: '${ENVIRONMENT:-development}'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: [] # No alertmanager configured

scrape_configs:
  # Spring Boot Application
  - job_name: 'pandacare-auth-profile'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: ['auth-profile:8081']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
        - targets: [ 'node-exporter:9100' ]
    scrape_interval: 15s        # Increased from 5s (was too frequent)
    scrape_timeout: 10s         # Increased timeout
    metrics_path: '/metrics'
    honor_labels: true

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s