# .github/workflows/build.yml
name: Build Spring App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner

    env:
      DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
      DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
      DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_MS: ${{ secrets.JWT_EXPIRATION_MS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set gradlew as executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper (skip tests and jacoco)
        run: ./gradlew build -x test -x jacocoTestReport

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: build/libs/*.jar
