name: Deploy After Build

on:
  workflow_run:
    workflows: ["Build Spring App"]  # Name of the first workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            cd /appl
            rm -f app.jar
            cp /actions-runner/_work/auth-profile/auth-profile/build/libs/auth-profile-0.0.1-SNAPSHOT.jar app.jar
            nohup java -jar app.jar > app.log 2>&1 &
