name: Deploy After Build

on:
  workflow_run:
    workflows: ["Build Spring App"]  # Name of the first workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop app.service || true
            cp /actions-runner/_work/auth-profile/auth-profile/build/libs/auth-profile-0.0.1-SNAPSHOT.jar /appl/app.jar
            sudo systemctl start app.service
            sudo systemctl status app.service --no-pager
