name: Java CI with Gradle on Amazon Linux 2023

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read

    env:
      DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
      DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
      DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_MS: ${{ secrets.JWT_EXPIRATION_MS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Stop all Gradle daemons
        run: ./gradlew --stop

      - name: Kill any remaining Gradle processes
        run: pkill -f "GradleDaemon" || true
        continue-on-error: true

      - name: Build with Gradle Wrapper
        run: ./gradlew build -Dspring.profiles.active=test --no-daemon -Dorg.gradle.jvmargs="-Xmx512m -XX:MaxMetaspaceSize=256m"

      - name: Stop existing application (if running)
        run: |
          if pgrep -f auth-profile; then
            pkill -f auth-profile || true
          fi
        continue-on-error: true

      - name: Run application
        run: |
          JAR_FILE=$(ls build/libs/auth-profile-*.jar | grep -vE 'plain|sources|tests' | head -n 1)
          echo "Using JAR: $JAR_FILE"
          nohup java -jar "$JAR_FILE" > auth-profile.log 2>&1 &
          echo "Application started"
          sleep 15
          if pgrep -f auth-profile; then
            echo "✅ Application is running"
          else
            echo "❌ Application failed to start"
            cat auth-profile.log
            exit 1
          fi
